export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL"

export const GET_PROJECT_DETAILS_REQUEST = "GET_PROJECT_DETAILS_REQUEST"
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS"
export const GET_PROJECT_DETAILS_FAIL = "GET_PROJECT_DETAILS_FAIL"
export const GET_PROJECT_DETAILS_RESET = "GET_PROJECT_DETAILS_RESET"